version: "3"
services:
  app:
    image: ggilman/hamclock:latest
    container_name: hamclock
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8081:8081
    volumes:
      - /mnt/nas_public/docker/hamclock:/config
